### ISSUE TITLE
Server fails to load SpaceEngineers.ObjectBuilders.dll

### ISSUE THREAD

**Issue by Nooby1** [mmmaxwwwell/space-engineers-dedicated-docker-linux#1]
` setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.

ing stderr to '/root/Steam/logs/stderr.txt'

on file ./public/steambootstrapper_english.txt which appeared to exist failed!!!

erifying installation...

ownloading Update...

!! Fatal Error: Steamcmd needs to be online to update. Please confirm your network connection and try again.

0/threadtools.cpp (3659) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x56ef2f10/0x0xf7c0bb'

07 17:54:07.320: App Version: 01_197_073

07 17:54:07.369: Is official: True [NO][NIS][NAMP]

07 17:54:07.372: Environment.ProcessorCount: 24

07 17:54:07.388: Environment.OSVersion: Microsoft Windows 7 Professional (Microsoft Windows NT 6.1.7601 Service Pack 1)

07 17:54:07.388: Environment.CommandLine: "Z:\appdata\space-engineers\SpaceEngineersDedicated\DedicatedServer64\SpaceEngineersDedicated.exe" -noconsole -path Z:\appdata\space-engineers\SpaceEngineersDedicated -ignorelastsession

07 17:54:07.388: Environment.Is64BitProcess: True

07 17:54:07.388: Environment.Is64BitOperatingSystem: True

07 17:54:07.390: Environment.Version: .NET Framework 4.8.3761.0

07 17:54:07.391: Environment.CurrentDirectory: Z:\appdata\space-engineers\SpaceEngineersDedicated\DedicatedServer64

07 17:54:07.391: CPU Info: Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz

does not meet minimum requirements, forcing Experimental mode

ould not load necessary assembly dependencies. C# redistributable may be missing. Affected file: file:///Z:\appdata\space-engineers\SpaceEngineersDedicated\DedicatedServer64\SpaceEngineers.ObjectBuilders.dll

`

**Comment by mmmaxwwwell** [comment]
Please don't just dump the log output here.

I would look into this line: "!! Fatal Error: Steamcmd needs to be online to update. Please confirm your network connection and try again.". 

Did you try other containers like devidians? 
https://github.com/Devidian/docker-spaceengineers

**Comment by Nooby1** [comment]
Hi, the file exists in the install, and it is an issue with devidan container too
The base os is centos8
Do you currently have this container working / running on any system?

**Comment by mmmaxwwwell** [comment]
Yeah, try ubuntu 20.04 or the latest lts debian as a base. Also, are you building this yourself or using the dockerhub image?
