### ISSUE TITLE
131 Error after placing SpaceEngineers-Dedicated.cfg in correct folder

### ISSUE THREAD

**Issue by DavidPackard** [mmmaxwwwell/space-engineers-dedicated-docker-linux#10]
Hi, I've followed the setup guide and used the start script to run the server. I've placed the world in the world folder, and the server config file in ./appdata/space-engineers/config/SpaceEngineers-Dedicated.cfg/ (which is a folder, not a file) however, the container keeps giving a 131 error code.

I have tried swapping the SpaceEngineers-Dedicated.cfg for the folder, and that results in docker mounting errors

**Comment by mmmaxwwwell** [comment]
Check permissions on the file. My first suggestion would be to swap the folder and file, but you have already tried that. Not sure whats going on with your setup. I would recommend deleting everything and using the start script to get a default world loaded, and then customize from there. If your still having trouble, reach out to me on the keen swh discord.

**Comment by mmmaxwwwell** [comment]
Oh, and make sure you run the start script with whatever user has uid 1000.
