### ISSUE TITLE
Exception while loading world: Input string was not in a correct format. v 1.198.024

### ISSUE THREAD

**Issue by kennethx** [mmmaxwwwell/space-engineers-dedicated-docker-linux#11]
Hello. 

Been using this docker for some time, but on todays update something broke, and every time i do ./start it ends with: 
"Exception while loading world: Input string was not in a correct format."

This started happening in v 1.192.024, before the update earlier today it was working.

**Comment by mmmaxwwwell** [comment]
Can you open your sandbox files and verify they aren't corrupt?

**Comment by turkishviking** [comment]
hi,

I have the same bug, with a fresh install

**Comment by turkishviking** [comment]
If I can help, I'm here

**Comment by turkishviking** [comment]
I have tried to replace all the content in the "World" folder by some new one, it doesn't work

**Comment by mmmaxwwwell** [comment]
We think we've isolated the issue with the help of one of the SE devs, going to test out a few fixes after work today.

**Comment by turkishviking** [comment]
wow cool! thank you!

**Comment by mmmaxwwwell** [comment]
It looks like we're stuck at the moment.

An analytics module in the game is attempting to call Kernel32.dll > GetGeoInfo(GeoTypeEnum.Lattitude) and GetGeoInfo(GeoTypeEnum.Longitude).

Wine hasn't implemented that syscall, and is returning an empty string.

https://github.com/wine-mirror/wine/blob/e909986e6ea5ecd49b2b847f321ad89b2ae4f6f1/dlls/kernelbase/locale.c#L4289

The game throws an error when trying to parse said empty string.

**Comment by turkishviking** [comment]
Thank you for the feedback. I will see if I can help tomorrow

**Comment by mmmaxwwwell** [comment]
Keens releasing a hotfix soon that should resolve this

**Comment by mmmaxwwwell** [comment]
Hotfix delayed until next week, sit tight

**Comment by kennethx** [comment]
Thanks for the update

**Comment by Fischchen** [comment]
Since wine seems to be Open Source would it be possible to compile a version that just returns hard coded coordinates every time its asked?
I can't write C, but maybe someone can write and compile this? It would fix the problem until the Hotfix is out. (I think)

**Comment by mmmaxwwwell** [comment]
Theoretically it's possible, but I'm going to wait for keen.

**Comment by turkishviking** [comment]
That's i wanted to do, but honestly it's a lot of work (the compilation, and make a clean compiled version of wine), if keen works on a hot-fix, i will wait for it, I mean I'm not sure to finish a patched version of wine before it.

**Comment by Fischchen** [comment]
Hotfix is out!!!

**Comment by mmmaxwwwell** [comment]
Awesome!!! Just start the container, it should pull the update automatically

**Comment by mmmaxwwwell** [comment]
I'll update the readme after I confirm it working properly

**Comment by Fischchen** [comment]
> Awesome!!! Just start the container, it should pull the update automatically

well i had the only other issue that is currently open and had to recompile it, but it seems to be working

**Comment by turkishviking** [comment]
nice !

**Comment by mmmaxwwwell** [comment]
its working again, closing this
