### ISSUE TITLE
Exit Code 130

### ISSUE THREAD

**Issue by Zolkennn** [mmmaxwwwell/space-engineers-dedicated-docker-linux#14]
Hello, I have a slight problem whith the exit code 130. 
As soon as I start my server docked lauch but the terminal sais 2 time World folder does not exist, exiting.
I dont know why because i have test with the default world or one of mine but neither works :/
I specify that I have both in /appdata/space-engineers/config/World

![Capture d’écran 2021-06-29 213557](https://user-images.githubusercontent.com/61419525/123857015-11761980-d922-11eb-8f0d-d45d0eaf2231.png)

Sorry for my bad english, I'm french :/

**Comment by mmmaxwwwell** [comment]
Please don't open issues like "It doesn't work on my machine", and not include any additional info.

**Comment by mmmaxwwwell** [comment]
Also, join the keen swh discord and ask in the #linux channel there, maybe someone can help.
