### ISSUE TITLE
World & backups gone after update

### ISSUE THREAD

**Issue by pridit** [mmmaxwwwell/space-engineers-dedicated-docker-linux#15]
Hey, not too sure what happened here but there was an update today. I restarted the container to perform this update, and for some reason I guess it may have removed the directory or something? I'm honestly not sure what happened or why this all disappeared when the container started up again. The configuration wasn't touched so I just don't understand why the world & backups went missing. Any ideas?

https://pastebin.com/XA3mAgy2

**Comment by mmmaxwwwell** [comment]
Can you post the contents of your docker-compose.yml here?

**Comment by pridit** [comment]
```
docker run --name=space-engineers --restart always -p "27016:27016/udp" \
  -v $(pwd)/appdata/space-engineers/config/World:/appdata/space-engineers/World\
  -v $(pwd)/appdata/space-engineers/bins/SpaceEngineersDedicated:/appdata/space-engineers/SpaceEngineersDedicated\
  -v $(pwd)/appdata/space-engineers/bins/steamcmd:/home/se/.steam\
  -v $(pwd)/appdata/space-engineers/config/SpaceEngineers-Dedicated.cfg:/appdata/space-engineers/SpaceEngineersDedicated/SpaceEngineers-Dedicated.cfg\
  mmmaxwwwell/space-engineers-dedicated-docker-linux:latest

**Comment by pridit** [comment]
I think this ended up being a permission issue and it wasn't writing, but with a few tests I did before they were so it probably wasn't writing at all. I'm running into that a lot with this. Would be great if we could pass a UID/GID but appreciate that this is a hobby thing.

**Comment by mmmaxwwwell** [comment]
I wasn't sure how to fix that without breaking existing installs, do you have an idea?

**Comment by pridit** [comment]
Sorry I'm not too familiar with how you have set things up to offer much insight here, especially combined with the craziness that is wine.

I'm just using the `permissions` branch for the time being which is solving this. In terms of breaking existing installs can't you wrap things in conditionals if UID/GID is supplied? If not, introduce versioning and use an image with a new tag? Alternatively, chown with `$(whoami):$(id -g)` which I don't think would break existing installs?

Maybe some influence can be derived from the [Rust image](https://github.com/Didstopia/rust-server/commit/ad95963134a412dd03214cf512964154b733e045)?

**Comment by mmmaxwwwell** [comment]
Good idea, I'll take a look. I was doing some thinking, and I think the best idea would be to detect the uid and guid of the user running the binary at runtime, with some sensible defaults set.

I'm closing this.
