### ISSUE TITLE
How to restart server from within container?

### ISSUE THREAD

**Issue by DeveloperBlue** [mmmaxwwwell/space-engineers-dedicated-docker-linux#17]
How would I go about restarting the server from within the container?

Restarting the container itself seems like a bad idea as that does an uncontrolled shutdown of the server and running `docker exec` doesn't connect to the running server.

**Comment by mmmaxwwwell** [comment]
The only difference between a controlled shutdown and an uncontrolled shutdown is if the server saves before hand. As an admin, I think you can type "/save" and "/stop" in the game chat, and it'll save and quit, then be restarted by the docker compose watchdog.

**Comment by mmmaxwwwell** [comment]
I bet you could also write a plugin that could save and stop the server on some event

**Comment by DeveloperBlue** [comment]
Just wanted to add that doing /save and /stop with auto-restart enabled did accomplish this. Thanks 👍
