### ISSUE TITLE
VRage client connection fails to connect

### ISSUE THREAD

**Issue by Tetrino** [mmmaxwwwell/space-engineers-dedicated-docker-linux#18]
Hey there, thank you so so much for this repo - it's exactly what I was looking for!

However I have hit a snag in that VRage doesn't seem to want to connect to the hosted server remotely. As far as I can tell, it may be due to a lack of elevated privileges (it never really worked without the dedicated server running in admin mode), however I was hoping you could shed some light on this? Remote API is enabled and all values are correct in VRage.

Less a bug more an enquiry. Feel free to close!

**Comment by Teacay1** [comment]
Yep I have the same issue.  The logs state that the Remoteclient is running and listening on Port 8080. However checking with netstat it shows no process listening on that port. 
So I assume it is not able to successfully start the Remoteclient?

**Comment by uggima** [comment]
Used this docker a few months ago.  When starting it up you pass it what ports to forward to the outside world, 8080 isn't included there if i remember correctly. I would guess it wouldn't be as simple as just adding in the port, but you could give it a try.

**Comment by Teacay1** [comment]
I've added the port 8080 in the docker-compose.yml file. Checking with netstat it now shows as listening on port 8080. I've additionally forwarded the port on my router but VRage is still not able to establish a connection (tried via local and public IP, hostname... no difference).
Would have been nice to be able to use the Remote Client but apart from that the server runs wonderfully, so thanks for the work mmmaxwwwell!

**Comment by mmmaxwwwell** [comment]
Hey thanks for the support,

I've never relied on that remote client to take care of anything so I'm not familiar with it. I have opened the ports and tried to connect a few times with no success.

The observations in this thread about not having the port open is correct. One would need to add an additional line in the ports section of docker-compose.yml to expose the service.

The reason it's not enabled by default, or commented out and left in docker-compose.yml, is it never worked for me.

I don't really know how to use the tool though so who knows, maybe I was doing it wrong.

If you get it working please let me know or submit a pull request.

For now I'm closing this. If you want some guidance or reading material to try and tackle it yourself, just comment to reopen and I'll get back to you.
