### ISSUE TITLE
Wine: Unhandled Exception

### ISSUE THREAD

**Issue by lukevad3r** [mmmaxwwwell/space-engineers-dedicated-docker-linux#19]
Hi the start script holds with error.
hear the tail of the log:

space-engineers-dedicated-docker-linux |    at SpaceEngineersDedicated.MyProgram.Main(String[] args)
space-engineers-dedicated-docker-linux | wine: Unhandled exception 0xe0434352 in thread d8 at address 000000007B01129D (thread 00d8), starting debugger...
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
space-engineers-dedicated-docker-linux | Redirecting stderr to '/home/wine/Steam/logs/stderr.txt'
space-engineers-dedicated-docker-linux | [  0%] Checking for available updates...
space-engineers-dedicated-docker-linux | [----] Verifying installation...
space-engineers-dedicated-docker-linux | Steam Console Client (c) Valve Corporation
space-engineers-dedicated-docker-linux | -- type 'quit' to exit --
space-engineers-dedicated-docker-linux | Loading Steam API...OK
space-engineers-dedicated-docker-linux |
space-engineers-dedicated-docker-linux | Connecting anonymously to Steam Public...OK
space-engineers-dedicated-docker-linux | Waiting for client config...OK
space-engineers-dedicated-docker-linux | Waiting for user info...OK
space-engineers-dedicated-docker-linux | "@sSteamCmdForcePlatformType" = "windows"
space-engineers-dedicated-docker-linux | Success! App '298740' already up to date.
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux |
space-engineers-dedicated-docker-linux | Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Exception from HRESULT: 0x8009001D
space-engineers-dedicated-docker-linux |    at SpaceEngineersDedicated.MyProgram.Main(String[] args)
space-engineers-dedicated-docker-linux | wine: Unhandled exception 0xe0434352 in thread d4 at address 000000007B01129D (thread 00d4), starting debugger...

**Comment by mmmaxwwwell** [comment]
Hey,

Sorry, I can't provide support for personal installations here, it's your mileage may vary. If there's a widespread issue I will take a look, but I can't guarantee compatibility with every distro or machine.

**Comment by mmmaxwwwell** [comment]
Have you used this before, and are now just encountering this on a new world? Or is this the first time you are trying it?

**Comment by lukevad3r** [comment]
The img never worked

**Comment by lukevad3r** [comment]
I'm using ubuntu server 20.04 and docker-compose and i followed the install instructions, with the ./start script

I can provide more information if needed, like log.files or programm versions

Please help I would realy love if this would work

So long, and thanks for all the fish!

**Comment by lukarolak** [comment]
Hey hey, I started a few servers on Ubuntu 20.04 and I have time to go over it with you @lukevad3r 

here is my discord username, poke me there Luka#2634

**Comment by lukevad3r** [comment]
wow that would be nice! I'll add you to my discord and would kontakt you on the weekend, if that would be okay for you.

**Comment by SeanOMik** [comment]
@lukarolak I'm getting the same error on my Ubuntu server. I send you a friend request on Discord (same username as it is here). If you could help me with it, that would be greatly appreciated.
