### ISSUE TITLE
Low ram allocation

### ISSUE THREAD

**Issue by OrigamiToast** [mmmaxwwwell/space-engineers-dedicated-docker-linux#20]
Don't really know what information to provide aside from the fact that even under load the process refuses to use over 2 gb

**Comment by mmmaxwwwell** [comment]
Sounds like something on your conputer is running in a 32 bit architecture, as the memory limit for 32 bit applications is 2gb. The container gladly will consume more than 2gb and does so at idle.

This is an issue with your computer, not the docker container.

Good luck.
