### ISSUE TITLE
Recover the save game from a running container

### ISSUE THREAD

**Issue by lukarolak** [mmmaxwwwell/space-engineers-dedicated-docker-linux#21]
Hi,
I acctidently deleted the whole folder with your repository, this ofcourse deleted the save game as well.

At the moment I have a working docker container and the server works, @mmmaxwwwell is it possilble to recover the save game from the container or wine?

Thanks a lot.

**Comment by mmmaxwwwell** [comment]
When you delete a file, usually the only the reference to the file is removed, not the file itself. It should be possible to get the world back using some disk recovery utility in theory, however your mileage may vary in practice.

**Comment by lukarolak** [comment]
Welp, I tried a lot of stuff and I've learned a lot on how your setup up wine and docker.

Strabgely in your docker-compose.yml you listed the volumes that you will use, but they do not show up when running docker volume ls

And I saw a way to increase performance, that I will try out in a couple of days. If it works I'll create a pull request.
