### ISSUE TITLE
start script can't mkdir

### ISSUE THREAD

**Issue by lukevad3r** [mmmaxwwwell/space-engineers-dedicated-docker-linux#24]
Please! I have tried everything (
made new user 
usermod -aG sudo tom
visudo
user ALL=(ALL:ALL)ALL
run ./start with sudo ./start
)

but nothing seams to be working. 

Please if someone can help me PLEASE!

space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"

wine --version
wine-6.0.1

docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by mmmaxwwwell** [comment]
If you are having permissions issues, you could try switching the mount points to a volume mount, instead of mapping a host folder into the container.

You would have to add a volumes section to the docker-compose.yml, modify each of the volume mounts, and pre-populate the world volume with the world data.

Closing this as this is a problem with your computer, not the repo.

**Comment by lukevad3r** [comment]
Thank I'm going to try that!
