### ISSUE TITLE
works fine on the first start but not on the 2nd and 3rd

### ISSUE THREAD

**Issue by imstupidwithlinux** [mmmaxwwwell/space-engineers-dedicated-docker-linux#28]
when you run the file the first time it works perfectly fine, but when you stop the server for whatever reason you cant start it again it exits with the code 255 which is not specified on here and it only works again when i downlaod and run the fresh file again.

is it possible to install mods?

**Comment by SvenM87** [comment]
I don't know you're problem with the exit code, but I'm struggling with mods too.
I added them to the dedicated config file but after 10 restarts it wouldn't download them. I will try adding them in the sandbox config in the world directory tomorrow.

**Comment by imstupidwithlinux** [comment]
I found the issue I needed to install wine then it works.

What if I drag the mods into the mods folder? Will it load them without adding them into the config cause I don't know how to add them in there

**Comment by SvenM87** [comment]
Here is how to add the mods in sandbox config (which I would try tomorrow):
https://www.gameserverkings.com/knowledge-base/space-engineers/space-engineers-mod/

And the other way is to add them in the config file located at "appdata/space-engineers/config". That should install the mods after a restart, but don't work for me for any reason.

**Comment by imstupidwithlinux** [comment]
Old I'll look into that, when I create a new world on my pc and drag it over with the mods I want to use it should apply everything right? Just theoretically

**Comment by imstupidwithlinux** [comment]
funfact I can't Test it cause I rebooted my server and it doesnt work anymore again back to the question I mentioned here

**Comment by SvenM87** [comment]
What's the problem now? Btw which Linux distro/version do u use?

**Comment by imstupidwithlinux** [comment]
Im using debian cause I began with raspberry pi, tried Ubuntu and i kinda don't like the commands over there 


It validate all the files then it boots up eine I think where usually then the world should start takes it a while until it says exit code 255 🤷‍♂️

**Comment by imstupidwithlinux** [comment]
![908CD39E-E6F3-45A6-A0DB-20E1840C4A77](https://user-images.githubusercontent.com/87829672/141253367-dfbfba07-4e0c-44b5-9871-ad7c94d6e252.png)
thats on the first start 
![0646CA63-C679-485E-A65A-A1A5622E0086](https://user-images.githubusercontent.com/87829672/141253396-434806b4-1c99-4db8-a0c1-0b116e1489f8.png)
and thats on all the other ones after the first

**Comment by SvenM87** [comment]
I created a game in solo play and uploaded the world to the server after a little bit patience and some restart and one reboot the server seems to be up and working.

**Comment by SvenM87** [comment]
Okay, the "no IP assigned" error is annoying, but u have to restart the container again and again, after 5-10 restarts it is working. The problem with stuck after "no console..." Is either patience or a reboot, I don't really have patience XD

**Comment by imstupidwithlinux** [comment]
As it was working yesterday i just ignored the error as I had the same message in windows cause I didn't set any ip and it worked

**Comment by imstupidwithlinux** [comment]
Just rebooted the machine a 5th time and it seems to be running...now trying to restart and then testing the mods

**Comment by imstupidwithlinux** [comment]
either mods doesnt work or the server is freaking out agian

**Comment by SvenM87** [comment]
I copied the world from local save game and it is running

**Comment by imstupidwithlinux** [comment]
With mods tho?

**Comment by SvenM87** [comment]
No, only the world folder. The mods then are downloaded.

**Comment by imstupidwithlinux** [comment]
I wanted to change the config how the world was called and on startup he was just like aight lemme replace this real quick with a fresh one
