### ISSUE TITLE
Error 53 

### ISSUE THREAD

**Issue by IndexOutOfMJ** [mmmaxwwwell/space-engineers-dedicated-docker-linux#30]
My error when i run the ./start file

`space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
space-engineers-dedicated-docker-linux | Sandbox.sbc file does not exist, exiting.
space-engineers-dedicated-docker-linux | Sandbox.sbc file does not exist, exiting.
space-engineers-dedicated-docker-linux | SpaceEngineers-Dedicated.cfg file does not exist, exiting.
space-engineers-dedicated-docker-linux | SpaceEngineers-Dedicated.cfg file does not exist, exiting.
space-engineers-dedicated-docker-linux | Sandbox.sbc file does not exist, exiting.
space-engineers-dedicated-docker-linux | Sandbox.sbc file does not exist, exiting.
space-engineers-dedicated-docker-linux | SpaceEngineers-Dedicated.cfg file does not exist, exiting.
space-engineers-dedicated-docker-linux | SpaceEngineers-Dedicated.cfg file does not exist, exiting.
space-engineers-dedicated-docker-linux | SpaceEngineers-Dedicated.cfg file does not exist, exiting.
space-engineers-dedicated-docker-linux | SpaceEngineers-Dedicated.cfg file does not exist, exiting.
space-engineers-dedicated-docker-linux | SpaceEngineers-Dedicated.cfg file does not exist, exiting.
space-engineers-dedicated-docker-linux | SpaceEngineers-Dedicated.cfg file does not exist, exiting.
space-engineers-dedicated-docker-linux | SpaceEngineers-Dedicated.cfg file does not exist, exiting.
space-engineers-dedicated-docker-linux | SpaceEngineers-Dedicated.cfg file does not exist, exiting.
space-engineers-dedicated-docker-linux | SpaceEngineers-Dedicated.cfg file does not exist, exiting.
space-engineers-dedicated-docker-linux | SpaceEngineers-Dedicated.cfg file does not exist, exiting.
space-engineers-dedicated-docker-linux | SpaceEngineers-Dedicated.cfg file does not exist, exiting.
space-engineers-dedicated-docker-linux | ls: cannot access '/appdata/space-engineers/Plugins/*.dll': No such file or directory
space-engineers-dedicated-docker-linux | mkdir: cannot create directory '/home/wine/.steam/steamcmd': Permission denied
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/': Not a directory
space-engineers-dedicated-docker-linux | cp: cannot create regular file '/home/wine/.steam/steamcmd/linux32/': No such file or directory
space-engineers-dedicated-docker-linux | /usr/games/steamcmd: 24: exec: /home/wine/.steam/steamcmd/steamcmd.sh: not found
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 3: /home/wine/.bash_profile: No such file or directory
space-engineers-dedicated-docker-linux | /entrypoint-space_engineers.bash: line 4: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
space-engineers-dedicated-docker-linux | wine: cannot find L"/appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/SpaceEngineersDedicated.exe"
`

**Comment by brunofporto** [comment]
Having the same issue. Adding Wine beforehand did not help.

**Comment by mmmaxwwwell** [comment]
This is a permissions issue. The container runs the space engineers user as user and group id 1000. If the user you ran the ./start script from isn't user/group 1000 on your machine, you will see this issue.

I added a little check in the ./start script to chown the files to 1000:1000 if you are not that user. This should let new users unfamiliar with unix permissions get started while not breaking existing installs.
