### ISSUE TITLE
Crossplay support

### ISSUE THREAD

**Issue by PaPa1ya** [mmmaxwwwell/space-engineers-dedicated-docker-linux#31]
Hello, does the server support crossplay? Is it possible to change the server type to EOS?

**Comment by mmmaxwwwell** [comment]
Not sure, you should try it and report back your findings.

**Comment by mmmaxwwwell** [comment]
I checked with the guys in the #linux channel, and it seems like it should be possible to start the server in EOS mode using your own SpaceEngineers-Dedicated.cfg, but I'm not going to add explicit support for it. YMMV, good luck.
