### ISSUE TITLE
Server downloading to the wrong directory

### ISSUE THREAD

**Issue by BaIthamel** [mmmaxwwwell/space-engineers-dedicated-docker-linux#33]
When I run the script I get the error `Please use force_install_dir before logon!` and space engineers ends up in .steam/steamapps/common. I can't work out a functioning steamcmd string to get it to download into /appdata.
This looks like it's related to some change to steamcmd that is referenced in https://github.com/ValveSoftware/steam-for-linux/issues/8298.

**Comment by mmmaxwwwell** [comment]
I fired up 2 new worlds today and didn't experience this, can you elaborate on what you are doing?

**Comment by mmmaxwwwell** [comment]
Reading that issue more, I get it now.

According to that issue, this is what you want
 
```​runuser -l wine bash -c ​'​steamcmd +force_install_dir /appdata/space-engineers/SpaceEngineersDedicated +login anonymous +@sSteamCmdForcePlatformType windows +app_update 298740 +quit​'```

Typing this on my phone laying in bed. I probably won't have time to test this for a week or so, hope that gets you going in the interim.

**Comment by BaIthamel** [comment]
As least one of the characters in your example code is visually the same as the characters in the code I constructed but it does not run when pasted into the console. `runuser -l wine bash -c 'steamcmd +force_install_dir /appdata/space-engineers/SpaceEngineersDedicated +login anonymous +@sSteamCmdForcePlatformType windows +app_update 298740 +quit'`
This is visually identical but unfortunately does not result in the download ending up in appdata. It still ends up in steamapps/common.
As a side note there is no confirmation that the force_install_dir is running, all of the other commands prompt some readable response from steamcmd. Do you get a confirmation that the install directory has changed?

I read that some issues were caused by passing multiple arguments to steamcmd so I tried using +runscript to this script

```
    @sSteamCmdForcePlatformType windows
    force_install_dir /appdata/space-engineers/SpaceEngineersDedicated
    login anonymous
    app_update 298740
    quit
```
This also had no success.

**Comment by BaIthamel** [comment]
this is what happens when I try to manually set the install directory, I am not familiar with steamcmd so I do not know if it should respond with confirmation or not, But it seems like it should.
![image](https://user-images.githubusercontent.com/10753531/152766156-683fcaa3-6c48-4cf0-b699-ec59efefd220.png)

**Comment by BaIthamel** [comment]
I found it. It was a permission issue. The appdata directory and subdirectories were created by docker as linked volumes and were owned by root. I changed their ownership to debian/wine and it worked.

The issue is not with this repo, it is with steamcmd for failing silently.
