### ISSUE TITLE
Torch Server

### ISSUE THREAD

**Issue by IdkWhosThis** [mmmaxwwwell/space-engineers-dedicated-docker-linux#39]
I would like to host a dedicated SE server on my Ubuntu 20.04 server and found this repository as the best way to do so. I have also discovered Torch server, which has special Plugins, for improving the server performance for example. Would it be possible to implement Torch into this repository? Or if anyone knows how to edit this to add Torch? 

I have also noticed that this supports some Plugins, but its not said which plugins does it support. Are there any performance plugins that this does support? Something like Torch does have?

**Comment by mmmaxwwwell** [comment]
I will not be adding torch support. You are free to fork the repo and try it yourself.

Torch plugins are different from and incompatible with dedicated server plugins. 

If you need some help figuring out the plugins for the DS or torch, ask around on the keen discord or on the torch discord respectively.

**Comment by IdkWhosThis** [comment]
The problem why I needed Torch is that I for some reason am uanble to host the server. Every time I turn on the server and join, there is regularly a rubberbending, not only for me, but for my friends (with better internet connection and ping) too. The specs I'm hosting on are AMD EPYC 7282 8-Core CPU with 30Gbs of ram, which I believe should be enough for hosting a SE server, or no?
