### ISSUE TITLE
[Question] Is it possible to have torchapi server instead of the DS provided by Keen?

### ISSUE THREAD

**Issue by Serenfo** [mmmaxwwwell/space-engineers-dedicated-docker-linux#41]
Is it possible to have a docker container with TorchApi instead of the editor's?

**Comment by mmmaxwwwell** [comment]
theoretically yes. You'll have to adjust some file paths and potentially some of the winetricks stuff as well as the start command for torch. I will not be implementing this due to my personal experiences with the torch maintainers.
