### ISSUE TITLE
Error "sudo: docker-compose: command not found"

### ISSUE THREAD

**Issue by Speijker** [mmmaxwwwell/space-engineers-dedicated-docker-linux#44]
Trying to run the start script, it returns twice the line `sudo: docker-compose: command not found`

![IMG_20220516_105337](https://user-images.githubusercontent.com/28538079/168556044-45eee7a0-d6ea-4f9e-b1dc-2320854fb590.jpg)

docker compose installation checked with `docker compose version`

**Comment by Speijker** [comment]
"fixed" by removing '-' from line in start script

Same issue applies to the stop script

**Comment by mmmaxwwwell** [comment]
You're missing the docker-compose executable.

https://stackoverflow.com/questions/66514436/difference-between-docker-compose-and-docker-compose

**Comment by Speijker** [comment]
> You're missing the docker-compose executable.
> 
> https://stackoverflow.com/questions/66514436/difference-between-docker-compose-and-docker-compose

And so I did. Docker documentation for linux gave two options: default is only the plugin, but apparently I needed the standalone binary. (https://docs.docker.com/compose/install/)

**Comment by ghost** [comment]
docker-compose is being deprecated soon. Should probably consider converting commands to the `docker compose`  (docker-compose-plugin)
