### ISSUE TITLE
Backups not working

### ISSUE THREAD

**Issue by Lloldrin** [mmmaxwwwell/space-engineers-dedicated-docker-linux#45]
We have recently started playing using this image. The first two days went fine, but after a server reset (manual, had to do a rollback), the backups stopped being created. The logs say that the server was autosaving every 20 minutes, but when it reset again (automatically), it was empty, and the last backup was the day before. 

Is this a known issue or did I break something when I reset the world manually? 

When resetting manually: I deleted SANDBOX_0_0_0.sbsB5, Sandbox.sbc, and Pertam.vx2. Then I copied back a clean version of Pertam.vx2 and ran the start-script

**Comment by mmmaxwwwell** [comment]
Sandbox.sbc contains persisted save data, removing that would reset part of the world to it's initial state. I'm not sure about the vx2 files, and the sbsB5 files store modifications to the asteroids/planet voxels. Cleaning up those intermittently will improve server performance.

**Comment by Lloldrin** [comment]
Yeah, the initial reset worked fine, but after that it stopped acually autosaving. The logs said "Autosaving" every 20 minutes, but nothing was actually written to /config/World/Backup/

**Comment by mmmaxwwwell** [comment]
Try replacing sandbox.sbc, otherwise its probably a permissions issue. I've had reports of it failing silently when it can't save.

**Comment by SeBL4RD** [comment]
I have the same problem, the server does not save at all. 
I created my own cfg locally (and save), I imported the parameters from the base one (the Z directories and others). The server works, our password parameters, the number of slots are functional, the automatic saves are done (on the console), but the server does not save. Our files have not been modified since their creation. Is it a permission problem? I used Root in sftp to upload my world and cfg. Should I do some manipulation? Docker not using Root?

**Comment by mmmaxwwwell** [comment]
Sounds like a permissions problem to me

**Comment by mmmaxwwwell** [comment]
Check the owning user, group and permissions of the world folder

**Comment by SeBL4RD** [comment]
All files are owned by Root user. isn't that supposed to be the case?

**Comment by mmmaxwwwell** [comment]
So docker runs as the root user, but the server inside the container runs as uid 1000

**Comment by mmmaxwwwell** [comment]
So no, the world directory should be writable by uid 1000

**Comment by SeBL4RD** [comment]
Do you know a command to change the entire directory to uid 1000 rather than root?

**Comment by SeBL4RD** [comment]
This part of your script is not supposed to do it at each start?
`if [ "$(stat -c '%u' appdata)" != "1000" ]; then
    echo "Setting owner of appdata to UID 1000"
    sudo chown -R 1000:1000 appdata
fi`

**Comment by SeBL4RD** [comment]
Fixed, 
it was actually because of that.
I `chown -R 1000:1000 World` and that fixed the problem. It would be necessary to add to the script the automation of the rights of this folder and its files.

**Comment by SeBL4RD** [comment]
if [ "$(stat -c '%u' /root/space-engineers-dedicated-docker-linux/appdata/space-engineers/config/World)" != "1000" ]; then 
echo "Setting owner of World to UID 1000
sudo chown -R 1000:1000 /root/space-engineers-dedicated-docker-linux/appdata/space-engineers/config/World
fi

Something like this i suppose :)

**Comment by mmmaxwwwell** [comment]
Thank you for posting a followup with your solution
