### ISSUE TITLE
Cannot start new world - Premade world not found

### ISSUE THREAD

**Issue by Curucma** [mmmaxwwwell/space-engineers-dedicated-docker-linux#49]
I run into the problem that i can only start the docker once, after i stopped the container for some adjustmants i wanted to restart the container but the rold wont load.

2022-07-28 18:44:37.602: Server connected to Steam
2022-07-28 18:44:38.374: Server Name:
2022-07-28 18:44:38.374: World Name:
2022-07-28 18:44:38.409: Auto Restart Enabled
2022-07-28 18:44:38.635: Remote Server Listener started. Listening on port 8080
2022-07-28 18:44:42.240: Cannot start new world - Premade world not found

As you can see the Server name and world name is blanc.
I could really use some help i kinda new to docker.

**Comment by mmmaxwwwell** [comment]
Can you verify the permissions of the Dedicated server config?

**Comment by Curucma** [comment]
Im not sure what exactly u mean with the permission of the Dedicated server config

**Comment by mmmaxwwwell** [comment]
The file you edited

**Comment by mmmaxwwwell** [comment]
Also run it through an xml checker like https://www.xmlvalidation.com/

**Comment by Curucma** [comment]
I did try to give the user i use fot the server the SpaceEngineers-Dedicated.cfg but still cant load the world

**Comment by Curucma** [comment]
I have done a fresh reinstall that worked ty for ur help
