### ISSUE TITLE
experimental mode not triggering

### ISSUE THREAD

**Issue by TheMightyMcGrew** [mmmaxwwwell/space-engineers-dedicated-docker-linux#50]
I redact my previous statement, and instead offer that successfully enabling experimental mode did not fix the mods not loading issue. Where exactly do I place these mods? Ive tried putting them in every folder labeled  "mods" and even the Plugins folder

**Comment by ilmal** [comment]
This is a great documentation for how to download mods: 

https://www.gameserverkings.com/knowledge-base/space-engineers/space-engineers-mod/

You just need to edit the config file and add the mod IDs.

**Comment by mmmaxwwwell** [comment]
I pushed a fix for the mod loading issue to the v2 branch - please test and reopen this issue or open another if you're still having a problem
