### ISSUE TITLE
Server reverting to initial save - couldn't access file

### ISSUE THREAD

**Issue by gjaskula99** [mmmaxwwwell/space-engineers-dedicated-docker-linux#57]
**CURRENT BEHAVIOUR**
Currently running on Centos under Podman. Everything works fine unless container is being restarted. After that it reverts to the initial savefile I uploaded to the server. No progress is being saved.

**EXPECTED BEHAVIOUR**
It saves.

**POSSIBLE SOLUTION**
Log files claimed that "AlienI ID"can't be accessed despite its presence in the folder. I tried changing from survival star system to different world - empty creative without mods. Same result - now "sandbox.sbc"can't be accessed. I tried changing folder permissions to 777. Even run on new container with compose (only minor change was container's name). No result. Maybe the problem is Podman itself?

**SPECS**
32 GB ECC
Intel Xeon
2 TB in software RAID1
Rocky 9 64bit
cockpit-containers, docker compose 1.23

**LOGS AND SERVER CONFIG**
[SpaceEngineers-Dedicated.txt](https://github.com/mmmaxwwwell/space-engineers-dedicated-docker-linux/files/11218787/SpaceEngineers-Dedicated.txt)
[SpaceEngineersDedicated_20230413_055813403.txt](https://github.com/mmmaxwwwell/space-engineers-dedicated-docker-linux/files/11218788/SpaceEngineersDedicated_20230413_055813403.txt)
[SpaceEngineersDedicated_20230413_061930903.txt](https://github.com/mmmaxwwwell/space-engineers-dedicated-docker-linux/files/11218790/SpaceEngineersDedicated_20230413_061930903.txt)

**Comment by J37T3R** [comment]
I'm having this issue as well, running Debian and normal Docker. Game does not save.

Addendum: was able to solve the issue by completely remaking the container and rechecking permissions on both the folder and files. Not sure which one specifically did it but it works for me now.

**Comment by mmmaxwwwell** [comment]
@J37T3R thank you for the reply with solution
