### ISSUE TITLE
Help with Getting Started

### ISSUE THREAD

**Issue by Gnnome** [mmmaxwwwell/space-engineers-dedicated-docker-linux#60]
I have been trying to get this to work for the past few hours with not much success. I followed the instructions and cloned the repo and ran the start file. Everything seems to work other than some errors which I don't know if they matter. But when I try and get it to use my config that I generated on my windows box and try and use the world I created for the server. Nothing works, it doesn't seem to use my config because experimental mode is still off, the server's name is unchanged, and it resets the world folder with the default files. 

What am I doing wrong?

**Comment by mmmaxwwwell** [comment]
Hey, just a heads up, but that log file contains your steam ID and public IP address, might want to keep those to yourself. I removed the link.

**Comment by mmmaxwwwell** [comment]
It looks like the ds installs updates, then crashes a couple times before recovering and then starting the game. I'm not 100% sure what's going on but I have a hunch it has to do with the save files you've provided, I don't think you have them in the right location, or there might be some kind of permissions issue. You might try deleting everything, then running the start script, letting the server come up fully (wait for game ready in the log), then stop the server and replace the game files with your own, then start it. Make sure the files are owned by uid 1000. If that doesn't work, try making the permissions on the app data folder more permissive.

**Comment by Gnnome** [comment]
Oops, thanks, didn't even notice my ip. I'll try that, I figured it wasn't a perms problem because I thought the script was running with sudo perms, because it asks for my password. I wasn't sure where to but the save file because the config folder one wasnt working, so I kinda just put it all over.

**Comment by mmmaxwwwell** [comment]
closing, maybe the keenswh discord #linux channel could help.
