### ISSUE TITLE
Can I turn off server autoshutdown after 12 hours of work?

### ISSUE THREAD

**Issue by Spyman** [mmmaxwwwell/space-engineers-dedicated-docker-linux#61]
I would like to have a continuously running server. But after 12 hours of work I get the message
"Automatic stop after 12 hours and 0 minutes". Can you tell me how to remove the auto-stop? Maybe this is some kind of game setting, but I did not find it. Thanks for the help.

**Comment by xcoldfyrex** [comment]
Are you using Torch or a similar mod? The stock config does not come with a shutdown. It's just an automatic restart(the server will come right back up), set at 720 minutes(12 hours): 
```<AutoRestatTimeInMin>720</AutoRestatTimeInMin>```

**Comment by mmmaxwwwell** [comment]
If you, as an admin, stop the server in game by running /stop, does it restart on its own? If not, make sure the docker container is set to restart always on process exit.
