### ISSUE TITLE
Any easy way to fix file permissions?

### ISSUE THREAD

**Issue by AtFreezingPoint** [mmmaxwwwell/space-engineers-dedicated-docker-linux#63]
Due to a script malfunctioning on super-user, i'm now stranded with broken permissions on the server; i can get the docker container working but the appdata folder is surely ever so slightly fucked up, any ideas on how i can easily manage to get that working?

**Comment by mmmaxwwwell** [comment]
learn the unix permission system

https://en.wikibooks.org/wiki/A_Quick_Introduction_to_Unix/Permissions
