### ISSUE TITLE
Medival Engineers

### ISSUE THREAD

**Issue by pietru2004** [mmmaxwwwell/space-engineers-dedicated-docker-linux#68]
Can this image also run medival engineers server ?
communityedition 367970

**Comment by mmmaxwwwell** [comment]
out of scope, please feel free to fork the repo and give it a try on your own. I am available on the keen swh discord to answer questions to assist you.

**Comment by pietru2004** [comment]
modified some stuff and got it working...

**Comment by mmmaxwwwell** [comment]
That's awesome!!!  Maybe make a new repo so people can consume it? If you have any questions, reach out on discord and I'll give you a hand.

**Comment by pietru2004** [comment]
gona think about that... but way I made it work is not looking nice...

**Comment by pietru2004** [comment]
Zip with it... it is almost the same as SE img files, but changed stuff from space namespace to medival + game id for ME server and community edition beta arg when downloading srv
[medival.zip](https://github.com/mmmaxwwwell/space-engineers-dedicated-docker-linux/files/15369267/medival.zip)
