### ISSUE TITLE
Pull and run from dockerhub error

### ISSUE THREAD

**Issue by woeisme** [mmmaxwwwell/space-engineers-dedicated-docker-linux#7]
Instructions read:

>docker run --restart always -p "27016:27016/udp" \
  -v $(pwd)/appdata/space-engineers/config/World:/appdata/space-engineers/World\
  -v $(pwd)/appdata/space-engineers/bins/SpaceEngineersDedicated:/appdata/space-engineers/SpaceEngineersDedicated\
  -v $(pwd)/appdata/space-engineers/bins/steamcmd:/home/se/.steam\
  -v $(pwd)/appdata/space-engineers/config/SpaceEngineers-Dedicated.cfg:/appdata/space-engineers/SpaceEngineersDedicated/SpaceEngineers-Dedicated.cfg\
  mmmaxwwwell/space-engineers-dedicated-docker-linux:**wine6** 

But running 

>docker pull mmmaxwwwell/space-engineers-dedicated-docker-linux 

Results in fetching:
>mmmaxwwwell/space-engineers-dedicated-docker-linux:**latest**

Instructions should be updated to reflect correct suffix

**Comment by mmmaxwwwell** [comment]
fixed, will be merging to master soon. Thanks!
