### ISSUE TITLE
a few breaks

### ISSUE THREAD

**Issue by cpyarger** [mmmaxwwwell/space-engineers-dedicated-docker-linux#9]
I believe the world files are out of date, 
as well as the docker-compose volumes section do not allow for the config file to be loaded as a file, you need a full not relative path for that

**Comment by mmmaxwwwell** [comment]
Thanks for the report of the world files, I'll take a look after work.

I'm using relative paths on my machine, it's supported by docker compose. Are you using docker for windows to run it?

**Comment by cpyarger** [comment]
No, I am using docker on Linux

**Comment by mmmaxwwwell** [comment]
Take a look at this post, docker compose does support relative paths.

https://stackoverflow.com/questions/46907558/docker-compose-relative-paths-vs-docker-volume

I've seen docker glitch and start complaining about mounts and do other strange stuff pretty regularly. You might try rebooting your computer or restarting the docker service or the underlying containerd service. 

Thank you for your report of out of date world files.

I'm closing this issue.

**Comment by cpyarger** [comment]
When starting up, it tried mounting the file as a path, and therefore broke.

**Comment by mmmaxwwwell** [comment]
It absolutely works, check your paths.
